repos:
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v1.8.0'  
  hooks:
  - id: mypy
  
- repo: https://github.com/ambv/black
  rev: '23.12.1'
  hooks:
    - id: black

- repo: https://github.com/pycqa/isort
  rev: '5.13.0'
  hooks:
    - id: isort
      name: isort (python)

- repo: https://github.com/pycqa/flake8
  rev: '4.0.1'
  hooks:
  -   id: flake8
      args: [--max-line-length=131]